// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {context} from '../models';

export function Drivescheck():Promise<Array<backend.Skinfo>>;

export function FileLogger(arg1:Array<any>):Promise<void>;

export function GetConfigData():Promise<backend.Data>;

export function InitJSON():Promise<void>;

export function PinALocation(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function UnpinALocation(arg1:string):Promise<void>;

export function WriteConfigAsJson():Promise<void>;
