// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Drivescheck() {
  return window['go']['backend']['Config']['Drivescheck']();
}

export function FileLogger(arg1) {
  return window['go']['backend']['Config']['FileLogger'](arg1);
}

export function GetConfigData() {
  return window['go']['backend']['Config']['GetConfigData']();
}

export function InitJSON() {
  return window['go']['backend']['Config']['InitJSON']();
}

export function PinALocation(arg1) {
  return window['go']['backend']['Config']['PinALocation'](arg1);
}

export function Startup(arg1) {
  return window['go']['backend']['Config']['Startup'](arg1);
}

export function UnpinALocation(arg1) {
  return window['go']['backend']['Config']['UnpinALocation'](arg1);
}

export function WriteConfigAsJson() {
  return window['go']['backend']['Config']['WriteConfigAsJson']();
}
