// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {context} from '../models';

export function AddSelected(arg1:string):Promise<void>;

export function BeginDeletion(arg1:boolean):Promise<void>;

export function BeginTransfer(arg1:string):Promise<void>;

export function CopyCommand():Promise<void>;

export function CutCommand():Promise<void>;

export function FileRenamer(arg1:string,arg2:string):Promise<void>;

export function GetDir(arg1:string):Promise<Array<backend.SkDirEntry>>;

export function GetParent(arg1:string):Promise<string>;

export function GetPercentageCompletion():Promise<number>;

export function RemoveAllSelected():Promise<void>;

export function RemoveSelected(arg1:string):Promise<void>;

export function Renamer(arg1:string,arg2:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
