// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDoneWork(arg1) {
  return window['go']['backend']['Fops']['AddDoneWork'](arg1);
}

export function AddSelected(arg1) {
  return window['go']['backend']['Fops']['AddSelected'](arg1);
}

export function AddTotalWork(arg1) {
  return window['go']['backend']['Fops']['AddTotalWork'](arg1);
}

export function BeginDeletion(arg1) {
  return window['go']['backend']['Fops']['BeginDeletion'](arg1);
}

export function BeginTransfer(arg1) {
  return window['go']['backend']['Fops']['BeginTransfer'](arg1);
}

export function CopyCommand() {
  return window['go']['backend']['Fops']['CopyCommand']();
}

export function CutCommand() {
  return window['go']['backend']['Fops']['CutCommand']();
}

export function FileRenamer(arg1, arg2) {
  return window['go']['backend']['Fops']['FileRenamer'](arg1, arg2);
}

export function GetDir(arg1) {
  return window['go']['backend']['Fops']['GetDir'](arg1);
}

export function GetDirEvents(arg1) {
  return window['go']['backend']['Fops']['GetDirEvents'](arg1);
}

export function GetDirHTML(arg1) {
  return window['go']['backend']['Fops']['GetDirHTML'](arg1);
}

export function GetParent(arg1) {
  return window['go']['backend']['Fops']['GetParent'](arg1);
}

export function RemoveAllSelected() {
  return window['go']['backend']['Fops']['RemoveAllSelected']();
}

export function RemoveSelected(arg1) {
  return window['go']['backend']['Fops']['RemoveSelected'](arg1);
}

export function Renamer(arg1, arg2) {
  return window['go']['backend']['Fops']['Renamer'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['backend']['Fops']['Startup'](arg1);
}
