// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DirectoryHandler(arg1) {
  return window['go']['backend']['RegistryOptions']['DirectoryHandler'](arg1);
}

export function Executor(arg1) {
  return window['go']['backend']['RegistryOptions']['Executor'](arg1);
}

export function FileHandler(arg1) {
  return window['go']['backend']['RegistryOptions']['FileHandler'](arg1);
}

export function MenuInfoProvider(arg1) {
  return window['go']['backend']['RegistryOptions']['MenuInfoProvider'](arg1);
}

export function Startup(arg1) {
  return window['go']['backend']['RegistryOptions']['Startup'](arg1);
}
