// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Drivescheck() {
  return window['go']['main']['Config']['Drivescheck']();
}

export function GetConfigData() {
  return window['go']['main']['Config']['GetConfigData']();
}

export function LoadJson() {
  return window['go']['main']['Config']['LoadJson']();
}

export function PinALocation(arg1) {
  return window['go']['main']['Config']['PinALocation'](arg1);
}

export function WriteConfigAsJson() {
  return window['go']['main']['Config']['WriteConfigAsJson']();
}
