// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Drivescheck():Promise<Array<main.Skinfo>>;

export function FileLogger(arg1:Array<any>):Promise<void>;

export function GetConfigData():Promise<main.Data>;

export function InitJSON():Promise<void>;

export function PinALocation(arg1:string):Promise<void>;

export function UnpinALocation(arg1:string):Promise<void>;

export function WriteConfigAsJson():Promise<void>;
