// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Drivescheck():Promise<Array<string>>;

export function GetConfigData():Promise<main.Data>;

export function LoadJson():Promise<main.Data>;

export function PinALocation(arg1:string):Promise<void>;

export function WriteConfigAsJson():Promise<void>;
