// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddSelected(arg1:string):Promise<void>;

export function BeginDeletion():Promise<void>;

export function BeginTransfer(arg1:string):Promise<void>;

export function CopyCommand():Promise<void>;

export function GetDir(arg1:string):Promise<Array<main.SkDirEntry>>;

export function GetParent(arg1:string):Promise<string>;

export function GetPercentageCompletion():Promise<number>;

export function RemoveAllSelected():Promise<void>;

export function RemoveSelected(arg1:string):Promise<void>;

export function Renamer(arg1:string,arg2:string):Promise<void>;
