// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSelected(arg1) {
  return window['go']['main']['Fops']['AddSelected'](arg1);
}

export function BeginTransfer(arg1) {
  return window['go']['main']['Fops']['BeginTransfer'](arg1);
}

export function CopyCommand() {
  return window['go']['main']['Fops']['CopyCommand']();
}

export function GetDir(arg1) {
  return window['go']['main']['Fops']['GetDir'](arg1);
}

export function GetParent(arg1) {
  return window['go']['main']['Fops']['GetParent'](arg1);
}

export function GetPercentageCompletion() {
  return window['go']['main']['Fops']['GetPercentageCompletion']();
}

export function RemoveAllSelected() {
  return window['go']['main']['Fops']['RemoveAllSelected']();
}

export function RemoveSelected(arg1) {
  return window['go']['main']['Fops']['RemoveSelected'](arg1);
}

export function Renamer(arg1, arg2) {
  return window['go']['main']['Fops']['Renamer'](arg1, arg2);
}
