// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetDir(arg1:string):Promise<Array<main.SkDirEntry>>;

export function GetParent(arg1:string):Promise<string>;
