// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDir(arg1) {
  return window['go']['main']['Fops']['GetDir'](arg1);
}

export function GetParent(arg1) {
  return window['go']['main']['Fops']['GetParent'](arg1);
}
