// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DirectoryHandler(arg1:string):Promise<void>;

export function Executor(arg1:number):Promise<void>;

export function FileHandler(arg1:string):Promise<void>;

export function MenuInfoProvider(arg1:string):Promise<Array<string>>;
